apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-baks-infotrygd-feed
  namespace: teamfamilie
  labels:
    team: teamfamilie
  annotations:
    nginx.ingress.kubernetes.io/proxy-next-upstream-tries: '1'
spec:
  image: {{image}}
  port: 8094
  leaderElection: true
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
    failureThreshold: 10
  readiness:
    path: /internal/health/readyness
    initialDelay: 20
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
  vault:
    enabled: false
  gcp: # Database
    sqlInstances:
      - type: POSTGRES_17 # IF This is changed, all data will be lost. Read on nais.io how to upgrade
        tier: db-custom-1-3840
        name: familie-baks-infotrygd-feed-17
        autoBackupHour: 2
        pointInTimeRecovery: false
        diskAutoresize: true
        highAvailability: false
        databases:
          - name: familie-baks-infotrygd-feed
            envVarPrefix: DB
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
        groups:
          - id: "024bfb25-ead3-4c04-bbe1-1db3d3362188" # teamfamilie-forvaltning
      replyURLs:
        - "https://familie-baks-infotrygd-feed.intern.nav.no/swagger-ui/oauth2-redirect.html"
      singlePageApplication: true
  accessPolicy:
    inbound:
      rules:
        - application: familie-ks-sak
          cluster: prod-gcp
        - application: ida
          namespace: traktor
          cluster: prod-fss
        - application: infotrygd-feed-proxy
          namespace: teamfamilie
          cluster: prod-fss
        - application: infotrygd-feed-proxy-v2
          namespace: infotrygd
          cluster: prod-fss
    outbound:
      rules:
        - application: logging
          namespace: nais-system
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      memory: 576Mi
    requests:
      memory: 576Mi
      cpu: 250m
  ingresses:
    - https://familie-baks-infotrygd-feed.intern.nav.no
  secureLogs:
    enabled: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    - name: JDK_JAVA_OPTIONS
      value: "-XX:MinRAMPercentage=25.0 -XX:MaxRAMPercentage=75.0 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp"
  kafka:
    pool: nav-prod
