apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-baks-infotrygd-feed
  namespace: teamfamilie
  labels:
    team: teamfamilie
  annotations:
    nginx.ingress.kubernetes.io/proxy-next-upstream-tries: '1'
spec:
  image: {{image}}
  port: 8094
  leaderElection: true
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
    failureThreshold: 10
  readiness:
    path: /internal/health/readyness
    initialDelay: 20
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  vault:
    enabled: false
  gcp: # Database
    sqlInstances:
      - type: POSTGRES_14 # IF This is changed, all data will be lost. Read on nais.io how to upgrade
        tier: db-custom-1-3840
        name: familie-baks-infotrygd-feed
        autoBackupHour: 2
        pointInTimeRecovery: true
        diskAutoresize: true
        highAvailability: false
        databases:
          - name: familie-baks-infotrygd-feed
            envVarPrefix: DB
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
        groups:
          - id: "c62e908a-cf20-4ad0-b7b3-3ff6ca4bf38b" # teamfamilie-forvaltning
      tenant: trygdeetaten.no
      replyURLs:
        - "https://familie-baks-infotrygd-feed.intern.dev.nav.no/swagger-ui/oauth2-redirect.html"
      singlePageApplication: true
  accessPolicy:
    inbound:
      rules:
        - application: familie-ks-sak
          cluster: dev-gcp
        - application: ida
          namespace: traktor
          cluster: prod-fss
        - application: infotrygd-feed-proxy
          namespace: teamfamilie
          cluster: dev-fss
        - application: infotrygd-feed-proxy-v2
          namespace: infotrygd
          cluster: dev-fss
    outbound:
      rules:
        - application: logging
          namespace: nais-system

  replicas:
    min: 1
    max: 1
  resources:
    limits:
      memory: 1024Mi
    requests:
      memory: 512Mi
      cpu: 500m
  ingresses:
    - https://familie-baks-infotrygd-feed.intern.dev.nav.no
  secureLogs:
    enabled: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: preprod
    - name: JDK_JAVA_OPTIONS
      value: "-XX:MinRAMPercentage=25.0 -XX:MaxRAMPercentage=75.0 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp"

  kafka:
    pool: nav-dev
