apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-baks-infotrygd-feed
  namespace: teamfamilie
  labels:
    team: teamfamilie
  annotations:
    nginx.ingress.kubernetes.io/proxy-next-upstream-tries: '1'
spec:
  image: {{image}}
  port: 8094
  leaderElection: true
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
    failureThreshold: 10
  readiness:
    path: /internal/health/readyness
    initialDelay: 20
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  vault:
    enabled: false
  gcp: # Database
    sqlInstances:
      - type: POSTGRES_12 # IF This is changed, all data will be lost. Read on nais.io how to upgrade
        tier: db-custom-1-3840
        name: familie-baks-infotrygd-feed
        autoBackupTime: "02:00"
        pointInTimeRecovery: true
        diskAutoresize: true
        highAvailability: false
        databases:
          - name: familie-baks-infotrygd-feed
            envVarPrefix: DB
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    inbound:
      rules:
        - application: familie-ks-sak
          cluster: dev-gcp
        - application: ida
          namespace: traktor
          cluster: prod-fss
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 1024Mi
      cpu: "1"
    requests:
      memory: 512Mi
      cpu: 500m
  ingresses:
    - https://familie-baks-infotrygd-feed.dev.intern.nav.no
  secureLogs:
    enabled: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: preprod

    - name: JAVA_OPTS
      value: "-XX:MinRAMPercentage=25.0 -XX:MaxRAMPercentage=75.0 -XX:+HeapDumpOnOutOfMemoryError"
  kafka:
    pool: nav-dev
