name: Automerge Dependabot PRs

on:
  workflow_dispatch:

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - name: Automerge Dependabot PRs
        uses: navikt/automerge-dependabot@main
        with:
          token: ${{ steps.app-token.outputs.token }}
          minimum-age-of-pr: '3'
          ignored-dependencies: path-to-regexp@*
