name: Automerge Dependabot PRs

on:
  workflow_dispatch:

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Automerge Dependabot PRs
        uses: navikt/automerge-dependabot@main
        with:
          token: ${{ github.token }}
          minimum-age-of-pr: '3'
          ignored-dependencies: path-to-regexp@*
