name: Build-Deploy-Prod-GCP
on:
  push:
    branches:
      - 'main'
env:
  IMAGE: ghcr.io/navikt/familie-baks-infotrygd-feed:${{ github.sha }}
  IMAGE_LATEST: ghcr.io/navikt/familie-baks-infotrygd-feed:latest
jobs:
  deploy-to-prod:
    name: Bygg app/image, push til github, deploy til preprod-gcp og til prod-gcp
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-java@v3"
        with:
          java-version: "17"
          distribution: 'temurin'
          cache: 'maven'
      - name: Bygg med maven
        env:
          TESTCONTAINERS_RYUK_DISABLED: true
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B --no-transfer-progress package --settings .m2/maven-settings.xml --file pom.xml
      - name: Bygg Docker image
        run: |
          docker build -t $IMAGE .
      - name: Login to GitHub Container Registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker image med versjonstag
        run: docker push ${IMAGE}
      - name: Skriv ut docker-taggen
        run: echo 'Docker-tag er ${{ github.sha }} ' >> $GITHUB_STEP_SUMMARY
      - name: Deploy til dev-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .deploy/nais/app-preprod.yaml
      - name: Deploy til prod-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .deploy/nais/app-prod.yaml
