name: Build-Deploy-Preprod
on:
  workflow_dispatch:
jobs:
  deploy-to-dev:
    name: Bygg app/image, push til github, deploy til dev-gcp
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Bygg med maven
        env:
          TESTCONTAINERS_RYUK_DISABLED: true
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B --no-transfer-progress package --settings .m2/maven-settings.xml --file pom.xml
      - uses: nais/docker-build-push@v0
        id: docker-push
        if: github.triggering_actor != 'dependabot[bot]'
        with:
          team: teamfamilie
          push_image: true
          dockerfile: Dockerfile
          docker_context: .
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
      - name: Deploy til dev-gcp
        if: github.triggering_actor != 'dependabot[bot]'
        uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .deploy/nais/app-preprod.yaml
          IMAGE: ${{ steps.docker-push.outputs.image }}
