name: 'Remove Old Images'
on:
  workflow_dispatch:
  schedule:
    - cron: '5 12 * * *'

jobs:
  remove-images:
    name: 'Remove old images'
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/delete-package-versions@v5
        with:
          package-name: 'familie-baks-infotrygd-feed'
          package-type: 'container'
          min-versions-to-keep: 1
