name: Deploy familie-baks-infotrygd-feed-kafka-manager
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy familie-baks-infotrygd-feed-kafka-manager til dev
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .deploy/nais/kafka-manager/preprod/familie-baks-infotrygd-feed-kafka-manager.yml
      - name: Deploy familie-baks-infotrygd-feed-kafka-manager til prod
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .deploy/nais/kafka-manager/prod/familie-baks-infotrygd-feed-kafka-manager.yml
