name: Deploy kafka topics

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy barnetrygd_feed_topic til dev
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .deploy/nais/kafka/preprod/barnetrygd_feed_topic.yaml

      - name: Deploy barnetrygd_feed_topic til prod
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .deploy/nais/kafka/prod/barnetrygd_feed_topic.yaml

      - name: Deploy kontantstøtte_feed_topic til dev
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .deploy/nais/kafka/preprod/kontantstøtte_feed_topic.yaml

      - name: Deploy kontantstøtte_feed_topic til prod
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .deploy/nais/kafka/prod/kontantstøtte_feed_topic.yaml